### ISSUE TITLE
Missing requirement: requests

### ISSUE THREAD

**Issue by Philippe-Cholet** [e3oroush/open-spotify-dl#1]
Hi!
I tried your tool out of curiosity and it just works, so thanks!
However, I first tried to run it with pipx: `pipx run open_spotify_dl --url URL` and it failed because `requests` is not in your requirement file.
Therefore, I installed it with pipx, injected `requests` in it, then it worked fine.
So just `requests` missing in your requirement file.
Have a nice day!

**Comment by realEbi** [comment]
Hey man, thanks for your report. I will add it.
